elasticsearch:
    image: elasticsearch:2.1
    ports:
        - "9200:9200"
kibana:
    image: kibana:4.3
    ports:
        - "5601:5601"
    links:
        - "elasticsearch:elasticsearch"
filebeat:
    build: "./filebeat"
    links:
        - "elasticsearch:elasticsearch"
    volumes:
        - "/var/lib/docker:/var/lib/docker"
        - "./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml"